# Generated by Django 4.2.7 on 2026-03-06 00:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0002_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='school',
            field=models.CharField(blank=True, choices=[('SOSE', 'School of Science and Engineering'), ('SOH', 'School of Humanities'), ('JGSOM', 'John Gokongwei School of Management'), ('RGLSOSS', 'Dr. Rosita G. Leong School of Social Sciences'), ('GBSEALD', 'Gokongwei Brothers School of Education and Learning Design')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'MODERATOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('URGENT', 'Urgent'), ('VOLUNTEER', 'Volunteer Work'), ('OPPORTUNITY', 'Scholarship Opportunity')], db_index=True, default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='carry_over_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='required_hours',
            field=models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='student_id',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='total_hours_rendered',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='date_rendered',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SCHOLAR', 'Scholar'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], db_index=True, default='SCHOLAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', '-created_at'], name='scholarapp__categor_0d91c9_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['author'], name='scholarapp__author__15d083_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarprofile',
            index=models.Index(fields=['user'], name='scholarapp__user_id_d82fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarprofile',
            index=models.Index(fields=['student_id'], name='scholarapp__student_349c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['scholar', '-date_rendered'], name='scholarapp__scholar_104ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['created_by'], name='scholarapp__created_040559_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_email_verified'], name='scholarapp__role_a022e3_idx'),
        ),
    ]
