# Generated by Django 4.2.7 on 2026-03-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0004_moderatorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderatorprofile',
            old_name='aoffice_name',
            new_name='office_name',
        ),
    ]
