# Generated by Django 5.1.6 on 2026-04-09 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0005_rename_aoffice_name_moderatorprofile_office_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='scholarapp__categor_0d91c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='scholarapp__author__15d083_idx',
        ),
        migrations.AddField(
            model_name='announcement',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('URGENT', 'Urgent'), ('VOLUNTEER', 'Volunteer Work'), ('OPPORTUNITY', 'Opportunity'), ('FOODSTUBS', 'Food Stubs')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='required_hours',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
