# Generated by Django 5.1.6 on 2026-04-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0007_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FOODSTUB', 'Food Stub'), ('ENTERTAINMENT', 'Entertainment'), ('TRANSPORT', 'Transport'), ('WELLNESS', 'Wellness'), ('ACADEMIC', 'Academic')], max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('total_slots', models.IntegerField()),
                ('remaining_slots', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('FULL', 'Full')], default='ACTIVE', max_length=20)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLAIMED', 'Claimed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_applications', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarapp.voucher')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('voucher', 'scholar')},
            },
        ),
    ]
