# Generated by Django 6.0.4 on 2026-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0009_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('FULL', 'Full')], default='PENDING', max_length=20),
        ),
    ]
