# Generated by Django 6.0.4 on 2026-04-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0010_voucher_rejection_reason_alter_voucher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorprofile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderators', to='scholarapp.office'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='scholarapp.office'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['office'], name='scholarapp__office__cfa65a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['office', 'status'], name='scholarapp__office__2cf32d_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['created_by'], name='scholarapp__created_c7df02_idx'),
        ),
    ]
