# Generated by Django 6.0.4 on 2026-04-16 15:47

from django.db import migrations


def backfill_office_relationships(apps, schema_editor):
    """
    Backfill office foreign key relationships:
    1. Create Office records from unique moderator office_name values
    2. Map ModeratorProfile.office to the created Office records
    3. Map Voucher.office to created_by moderator's office
    """
    Office = apps.get_model('scholarapp', 'Office')
    ModeratorProfile = apps.get_model('scholarapp', 'ModeratorProfile')
    Voucher = apps.get_model('scholarapp', 'Voucher')
    
    # Step 1: Get all unique office names from ModeratorProfile
    unique_offices = set(
        ModeratorProfile.objects.values_list('office_name', flat=True).distinct()
    )
    
    # Create Office records and build mapping
    office_mapping = {}
    for office_name in unique_offices:
        if office_name:  # Skip empty office names
            office, created = Office.objects.get_or_create(
                name=office_name,
                defaults={}
            )
            office_mapping[office_name] = office
    
    # Step 2: Map ModeratorProfile records to their offices
    for mod_profile in ModeratorProfile.objects.all():
        if mod_profile.office_name in office_mapping:
            mod_profile.office = office_mapping[mod_profile.office_name]
            mod_profile.save()
    
    # Step 3: Map Voucher records to offices based on created_by moderator
    for voucher in Voucher.objects.select_related('created_by').all():
        # Try to get office from the moderator who created it
        try:
            moderator_profile = voucher.created_by.moderator_profile
            if moderator_profile.office:
                voucher.office = moderator_profile.office
                voucher.save()
        except:
            # If voucher created_by is not a moderator or no office assigned, skip
            pass


def reverse_backfill(apps, schema_editor):
    """
    Reverse operation: clear office FKs but keep Office records and office_name field.
    This allows safe rollback without data loss.
    """
    ModeratorProfile = apps.get_model('scholarapp', 'ModeratorProfile')
    Voucher = apps.get_model('scholarapp', 'Voucher')
    
    ModeratorProfile.objects.all().update(office=None)
    Voucher.objects.all().update(office=None)


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0011_add_office_fks'),
    ]

    operations = [
        migrations.RunPython(backfill_office_relationships, reverse_backfill),
    ]
