# Generated by Django 6.0.4 on 2026-04-17 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0012_backfill_office_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semester Settings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='penalty',
            name='hours_added',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='penalty_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='penalty',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='scholarapp.semestersettings'),
        ),
    ]
