# Generated by Django 6.0.4 on 2026-04-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarapp', '0013_semestersettings_penalty_hours_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersettings',
            name='penalties_processed',
            field=models.BooleanField(default=False),
        ),
    ]
